// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: extension.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyRole int32

const (
	CompanyRole_unknown_role CompanyRole = 0
	CompanyRole_manager_role CompanyRole = 1 // 主管
	CompanyRole_member_role  CompanyRole = 2 // 普通成员
)

// Enum value maps for CompanyRole.
var (
	CompanyRole_name = map[int32]string{
		0: "unknown_role",
		1: "manager_role",
		2: "member_role",
	}
	CompanyRole_value = map[string]int32{
		"unknown_role": 0,
		"manager_role": 1,
		"member_role":  2,
	}
)

func (x CompanyRole) Enum() *CompanyRole {
	p := new(CompanyRole)
	*p = x
	return p
}

func (x CompanyRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompanyRole) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_proto_enumTypes[0].Descriptor()
}

func (CompanyRole) Type() protoreflect.EnumType {
	return &file_extension_proto_enumTypes[0]
}

func (x CompanyRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompanyRole.Descriptor instead.
func (CompanyRole) EnumDescriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type SAEvent int32

const (
	SAEvent_unknown_ev        SAEvent = 0
	SAEvent_del_department_ev SAEvent = 1 // 删除部门
	SAEvent_del_user_ev       SAEvent = 2 // 删除成员
)

// Enum value maps for SAEvent.
var (
	SAEvent_name = map[int32]string{
		0: "unknown_ev",
		1: "del_department_ev",
		2: "del_user_ev",
	}
	SAEvent_value = map[string]int32{
		"unknown_ev":        0,
		"del_department_ev": 1,
		"del_user_ev":       2,
	}
)

func (x SAEvent) Enum() *SAEvent {
	p := new(SAEvent)
	*p = x
	return p
}

func (x SAEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SAEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_proto_enumTypes[1].Descriptor()
}

func (SAEvent) Type() protoreflect.EnumType {
	return &file_extension_proto_enumTypes[1]
}

func (x SAEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SAEvent.Descriptor instead.
func (SAEvent) EnumDescriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

type AreaType int32

const (
	AreaType_unknown_type AreaType = 0
	AreaType_home_type    AreaType = 1 // 家庭
	AreaType_company_type AreaType = 2 // 公司
)

// Enum value maps for AreaType.
var (
	AreaType_name = map[int32]string{
		0: "unknown_type",
		1: "home_type",
		2: "company_type",
	}
	AreaType_value = map[string]int32{
		"unknown_type": 0,
		"home_type":    1,
		"company_type": 2,
	}
)

func (x AreaType) Enum() *AreaType {
	p := new(AreaType)
	*p = x
	return p
}

func (x AreaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AreaType) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_proto_enumTypes[2].Descriptor()
}

func (AreaType) Type() protoreflect.EnumType {
	return &file_extension_proto_enumTypes[2]
}

func (x AreaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AreaType.Descriptor instead.
func (AreaType) EnumDescriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type GetAreaInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetAreaInfoReq) Reset() {
	*x = GetAreaInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaInfoReq) ProtoMessage() {}

func (x *GetAreaInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaInfoReq.ProtoReflect.Descriptor instead.
func (*GetAreaInfoReq) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *GetAreaInfoReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo        *UserInfo             `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	DepartmentInfos []*DepartmentBaseInfo `protobuf:"bytes,2,rep,name=department_infos,json=departmentInfos,proto3" json:"department_infos,omitempty"` // 所在部门
	AreaInfo        *Area                 `protobuf:"bytes,3,opt,name=area_info,json=areaInfo,proto3" json:"area_info,omitempty"`
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *GetUserInfoResp) GetDepartmentInfos() []*DepartmentBaseInfo {
	if x != nil {
		return x.DepartmentInfos
	}
	return nil
}

func (x *GetUserInfoResp) GetAreaInfo() *Area {
	if x != nil {
		return x.AreaInfo
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountName string `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	NickName    string `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	IsOwner     bool   `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type Area struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaId   uint64   `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AreaType AreaType `protobuf:"varint,3,opt,name=area_type,json=areaType,proto3,enum=proto.AreaType" json:"area_type,omitempty"`
}

func (x *Area) Reset() {
	*x = Area{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *Area) GetAreaId() uint64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetAreaType() AreaType {
	if x != nil {
		return x.AreaType
	}
	return AreaType_unknown_type
}

type DepartmentBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartmentId int32       `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name         string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CompanyRole  CompanyRole `protobuf:"varint,3,opt,name=company_role,json=companyRole,proto3,enum=proto.CompanyRole" json:"company_role,omitempty"`
}

func (x *DepartmentBaseInfo) Reset() {
	*x = DepartmentBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentBaseInfo) ProtoMessage() {}

func (x *DepartmentBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentBaseInfo.ProtoReflect.Descriptor instead.
func (*DepartmentBaseInfo) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *DepartmentBaseInfo) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DepartmentBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentBaseInfo) GetCompanyRole() CompanyRole {
	if x != nil {
		return x.CompanyRole
	}
	return CompanyRole_unknown_role
}

type DepartmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartmentId     int32             `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name             string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChildDepartments []*DepartmentInfo `protobuf:"bytes,3,rep,name=child_departments,json=childDepartments,proto3" json:"child_departments,omitempty"`
}

func (x *DepartmentInfo) Reset() {
	*x = DepartmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentInfo) ProtoMessage() {}

func (x *DepartmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentInfo.ProtoReflect.Descriptor instead.
func (*DepartmentInfo) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *DepartmentInfo) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DepartmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentInfo) GetChildDepartments() []*DepartmentInfo {
	if x != nil {
		return x.ChildDepartments
	}
	return nil
}

type GetDepartmentUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token         string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DepartmentIds []int32 `protobuf:"varint,2,rep,packed,name=department_ids,json=departmentIds,proto3" json:"department_ids,omitempty"`
}

func (x *GetDepartmentUsersReq) Reset() {
	*x = GetDepartmentUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentUsersReq) ProtoMessage() {}

func (x *GetDepartmentUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentUsersReq.ProtoReflect.Descriptor instead.
func (*GetDepartmentUsersReq) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepartmentUsersReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetDepartmentUsersReq) GetDepartmentIds() []int32 {
	if x != nil {
		return x.DepartmentIds
	}
	return nil
}

type GetDepartmentUsersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartmentUsers map[int32]*DepartmentUsers `protobuf:"bytes,1,rep,name=department_users,json=departmentUsers,proto3" json:"department_users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetDepartmentUsersResp) Reset() {
	*x = GetDepartmentUsersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentUsersResp) ProtoMessage() {}

func (x *GetDepartmentUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentUsersResp.ProtoReflect.Descriptor instead.
func (*GetDepartmentUsersResp) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{8}
}

func (x *GetDepartmentUsersResp) GetDepartmentUsers() map[int32]*DepartmentUsers {
	if x != nil {
		return x.DepartmentUsers
	}
	return nil
}

type DepartmentUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *DepartmentUsers) Reset() {
	*x = DepartmentUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentUsers) ProtoMessage() {}

func (x *DepartmentUsers) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentUsers.ProtoReflect.Descriptor instead.
func (*DepartmentUsers) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{9}
}

func (x *DepartmentUsers) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type SAEventInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event SAEvent `protobuf:"varint,1,opt,name=event,proto3,enum=proto.SAEvent" json:"event,omitempty"`
	Data  []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SAEventInfo) Reset() {
	*x = SAEventInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAEventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAEventInfo) ProtoMessage() {}

func (x *SAEventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAEventInfo.ProtoReflect.Descriptor instead.
func (*SAEventInfo) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{10}
}

func (x *SAEventInfo) GetEvent() SAEvent {
	if x != nil {
		return x.Event
	}
	return SAEvent_unknown_ev
}

func (x *SAEventInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BaseUserInfosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserIds []int32 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *BaseUserInfosReq) Reset() {
	*x = BaseUserInfosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseUserInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUserInfosReq) ProtoMessage() {}

func (x *BaseUserInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUserInfosReq.ProtoReflect.Descriptor instead.
func (*BaseUserInfosReq) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{11}
}

func (x *BaseUserInfosReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BaseUserInfosReq) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_extension_proto protoreflect.FileDescriptor

var file_extension_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xaf, 0x01, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44,
	0x0a, 0x10, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x7e,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x61,
	0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0xd3,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x10, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x5a, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x38, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x47,
	0x0a, 0x0b, 0x53, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x2a, 0x42, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x10, 0x01, 0x12,
	0x0f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x10, 0x02,
	0x2a, 0x41, 0x0a, 0x07, 0x53, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x76, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x64,
	0x65, 0x6c, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x76,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65,
	0x76, 0x10, 0x02, 0x2a, 0x3d, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x10, 0x02, 0x32, 0x99, 0x02, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x43, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x36, 0x0a, 0x0d, 0x53, 0x41, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData = file_extension_proto_rawDesc
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(file_extension_proto_rawDescData)
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_extension_proto_goTypes = []interface{}{
	(CompanyRole)(0),               // 0: proto.CompanyRole
	(SAEvent)(0),                   // 1: proto.SAEvent
	(AreaType)(0),                  // 2: proto.AreaType
	(*EmptyReq)(nil),               // 3: proto.emptyReq
	(*GetAreaInfoReq)(nil),         // 4: proto.GetAreaInfoReq
	(*GetUserInfoResp)(nil),        // 5: proto.GetUserInfoResp
	(*UserInfo)(nil),               // 6: proto.UserInfo
	(*Area)(nil),                   // 7: proto.Area
	(*DepartmentBaseInfo)(nil),     // 8: proto.DepartmentBaseInfo
	(*DepartmentInfo)(nil),         // 9: proto.DepartmentInfo
	(*GetDepartmentUsersReq)(nil),  // 10: proto.GetDepartmentUsersReq
	(*GetDepartmentUsersResp)(nil), // 11: proto.GetDepartmentUsersResp
	(*DepartmentUsers)(nil),        // 12: proto.DepartmentUsers
	(*SAEventInfo)(nil),            // 13: proto.SAEventInfo
	(*BaseUserInfosReq)(nil),       // 14: proto.BaseUserInfosReq
	nil,                            // 15: proto.GetDepartmentUsersResp.DepartmentUsersEntry
}
var file_extension_proto_depIdxs = []int32{
	6,  // 0: proto.GetUserInfoResp.user_info:type_name -> proto.UserInfo
	8,  // 1: proto.GetUserInfoResp.department_infos:type_name -> proto.DepartmentBaseInfo
	7,  // 2: proto.GetUserInfoResp.area_info:type_name -> proto.Area
	2,  // 3: proto.Area.area_type:type_name -> proto.AreaType
	0,  // 4: proto.DepartmentBaseInfo.company_role:type_name -> proto.CompanyRole
	9,  // 5: proto.DepartmentInfo.child_departments:type_name -> proto.DepartmentInfo
	15, // 6: proto.GetDepartmentUsersResp.department_users:type_name -> proto.GetDepartmentUsersResp.DepartmentUsersEntry
	6,  // 7: proto.DepartmentUsers.users:type_name -> proto.UserInfo
	1,  // 8: proto.SAEventInfo.event:type_name -> proto.SAEvent
	12, // 9: proto.GetDepartmentUsersResp.DepartmentUsersEntry.value:type_name -> proto.DepartmentUsers
	4,  // 10: proto.Extension.GetUserInfo:input_type -> proto.GetAreaInfoReq
	10, // 11: proto.Extension.GetDepartmentUsers:input_type -> proto.GetDepartmentUsersReq
	14, // 12: proto.Extension.GetBaseUserInfos:input_type -> proto.BaseUserInfosReq
	3,  // 13: proto.Extension.SANotifyEvent:input_type -> proto.emptyReq
	5,  // 14: proto.Extension.GetUserInfo:output_type -> proto.GetUserInfoResp
	11, // 15: proto.Extension.GetDepartmentUsers:output_type -> proto.GetDepartmentUsersResp
	12, // 16: proto.Extension.GetBaseUserInfos:output_type -> proto.DepartmentUsers
	13, // 17: proto.Extension.SANotifyEvent:output_type -> proto.SAEventInfo
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extension_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Area); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentUsersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAEventInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseUserInfosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extension_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		EnumInfos:         file_extension_proto_enumTypes,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_rawDesc = nil
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExtensionClient is the client API for Extension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExtensionClient interface {
	// 获取用户数据
	GetUserInfo(ctx context.Context, in *GetAreaInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	// 获取部门下所有成员
	GetDepartmentUsers(ctx context.Context, in *GetDepartmentUsersReq, opts ...grpc.CallOption) (*GetDepartmentUsersResp, error)
	// 根据用户id获取基础数据
	GetBaseUserInfos(ctx context.Context, in *BaseUserInfosReq, opts ...grpc.CallOption) (*DepartmentUsers, error)
	// Sa通知事件
	SANotifyEvent(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (Extension_SANotifyEventClient, error)
}

type extensionClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionClient(cc grpc.ClientConnInterface) ExtensionClient {
	return &extensionClient{cc}
}

func (c *extensionClient) GetUserInfo(ctx context.Context, in *GetAreaInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, "/proto.Extension/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) GetDepartmentUsers(ctx context.Context, in *GetDepartmentUsersReq, opts ...grpc.CallOption) (*GetDepartmentUsersResp, error) {
	out := new(GetDepartmentUsersResp)
	err := c.cc.Invoke(ctx, "/proto.Extension/GetDepartmentUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) GetBaseUserInfos(ctx context.Context, in *BaseUserInfosReq, opts ...grpc.CallOption) (*DepartmentUsers, error) {
	out := new(DepartmentUsers)
	err := c.cc.Invoke(ctx, "/proto.Extension/GetBaseUserInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) SANotifyEvent(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (Extension_SANotifyEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Extension_serviceDesc.Streams[0], "/proto.Extension/SANotifyEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &extensionSANotifyEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Extension_SANotifyEventClient interface {
	Recv() (*SAEventInfo, error)
	grpc.ClientStream
}

type extensionSANotifyEventClient struct {
	grpc.ClientStream
}

func (x *extensionSANotifyEventClient) Recv() (*SAEventInfo, error) {
	m := new(SAEventInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExtensionServer is the server API for Extension service.
type ExtensionServer interface {
	// 获取用户数据
	GetUserInfo(context.Context, *GetAreaInfoReq) (*GetUserInfoResp, error)
	// 获取部门下所有成员
	GetDepartmentUsers(context.Context, *GetDepartmentUsersReq) (*GetDepartmentUsersResp, error)
	// 根据用户id获取基础数据
	GetBaseUserInfos(context.Context, *BaseUserInfosReq) (*DepartmentUsers, error)
	// Sa通知事件
	SANotifyEvent(*EmptyReq, Extension_SANotifyEventServer) error
}

// UnimplementedExtensionServer can be embedded to have forward compatible implementations.
type UnimplementedExtensionServer struct {
}

func (*UnimplementedExtensionServer) GetUserInfo(context.Context, *GetAreaInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedExtensionServer) GetDepartmentUsers(context.Context, *GetDepartmentUsersReq) (*GetDepartmentUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentUsers not implemented")
}
func (*UnimplementedExtensionServer) GetBaseUserInfos(context.Context, *BaseUserInfosReq) (*DepartmentUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseUserInfos not implemented")
}
func (*UnimplementedExtensionServer) SANotifyEvent(*EmptyReq, Extension_SANotifyEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SANotifyEvent not implemented")
}

func RegisterExtensionServer(s *grpc.Server, srv ExtensionServer) {
	s.RegisterService(&_Extension_serviceDesc, srv)
}

func _Extension_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Extension/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).GetUserInfo(ctx, req.(*GetAreaInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_GetDepartmentUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).GetDepartmentUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Extension/GetDepartmentUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).GetDepartmentUsers(ctx, req.(*GetDepartmentUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_GetBaseUserInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseUserInfosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).GetBaseUserInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Extension/GetBaseUserInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).GetBaseUserInfos(ctx, req.(*BaseUserInfosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_SANotifyEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtensionServer).SANotifyEvent(m, &extensionSANotifyEventServer{stream})
}

type Extension_SANotifyEventServer interface {
	Send(*SAEventInfo) error
	grpc.ServerStream
}

type extensionSANotifyEventServer struct {
	grpc.ServerStream
}

func (x *extensionSANotifyEventServer) Send(m *SAEventInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _Extension_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Extension",
	HandlerType: (*ExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _Extension_GetUserInfo_Handler,
		},
		{
			MethodName: "GetDepartmentUsers",
			Handler:    _Extension_GetDepartmentUsers_Handler,
		},
		{
			MethodName: "GetBaseUserInfos",
			Handler:    _Extension_GetBaseUserInfos_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SANotifyEvent",
			Handler:       _Extension_SANotifyEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "extension.proto",
}
